name: CI/CD Deploy

on:
  push:
    branches:
      - main  # or 'master' if your default branch is still named 'master'

permissions:
  contents: write  # Grant write access to contents (including pushing to the repository)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build